//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalHusbandryOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimalHusbandryOption()
        {
            this.AnimalHusbandries = new HashSet<AnimalHusbandry>();
        }
    
        public int AnimalHusbandryOptionID { get; set; }
        public int AnimalHusbandryFieldID { get; set; }
        public string AnimalHusbandryOptionName { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalHusbandry> AnimalHusbandries { get; set; }
        public virtual AnimalHusbandryField AnimalHusbandryField { get; set; }
    }
}
