//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalHusbandry
    {
        public int AnimalHusbandryID { get; set; }
        public int MultiPARTProjectMultiPARTProjectID { get; set; }
        public int ResearchgroupResearchgroupID { get; set; }
        public int StrainID { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTimeOffset LastUpdatedOn { get; set; }
        public int AnimalHusbandryFieldID { get; set; }
        public Nullable<int> AnimalHusbandryOptionID { get; set; }
        public string Value { get; set; }
    
        public virtual AnimalHusbandryField AnimalHusbandryField { get; set; }
        public virtual AnimalHusbandryOption AnimalHusbandryOption { get; set; }
        public virtual MultiPARTProject MultiPARTProject { get; set; }
        public virtual Researchgroup Researchgroup { get; set; }
        public virtual Researchgroup Researchgroup1 { get; set; }
        public virtual Strain Strain { get; set; }
    }
}
