//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehavioralScore
    {
        public int BehavioralScoreID { get; set; }
        public int QuestionID { get; set; }
        public int UserDataentryAssignmentID { get; set; }
        public Nullable<int> Score { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTimeOffset LastUpdatedOn { get; set; }
        public string Comments { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual UserDataentryAssignment UserDataentryAssignment { get; set; }
    }
}
