//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataEntryOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataEntryOption()
        {
            this.DataEntryDetails = new HashSet<DataEntryDetail>();
        }
    
        public int DataEntryOptionID { get; set; }
        public int DataEntryFieldDataEntryFieldID { get; set; }
        public string DataEntryOptionName { get; set; }
        public string Status { get; set; }
    
        public virtual DataEntryField DataEntryField { get; set; }
        public virtual DataEntryField DataEntryField1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataEntryDetail> DataEntryDetails { get; set; }
    }
}
