//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataEntryDetailValue
    {
        public int DataEntryDetailID { get; set; }
        public string Value { get; set; }
    
        public virtual DataEntryDetail DataEntryDetail { get; set; }
    }
}
