//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataEntryDetail
    {
        public int DataEntryDetailID { get; set; }
        public System.DateTimeOffset StartTime { get; set; }
        public System.DateTimeOffset EndTime { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTimeOffset LastUpdatedOn { get; set; }
        public int DataEntryDataEntryID { get; set; }
    
        public virtual DataEntry DataEntry { get; set; }
        public virtual DataEntryDetailValue DataEntryDetailValue { get; set; }
        public virtual File File { get; set; }
        public virtual DataEntryOption DataEntryOption { get; set; }
    }
}
