//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administration> Administrations { get; set; }
        public virtual DbSet<AnimalAdministration> AnimalAdministrations { get; set; }
        public virtual DbSet<AnimalHusbandry> AnimalHusbandries { get; set; }
        public virtual DbSet<AnimalHusbandryField> AnimalHusbandryFields { get; set; }
        public virtual DbSet<AnimalHusbandryOption> AnimalHusbandryOptions { get; set; }
        public virtual DbSet<AnimalProcedure> AnimalProcedures { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<AnimalSupplier> AnimalSuppliers { get; set; }
        public virtual DbSet<BehavioralScore> BehavioralScores { get; set; }
        public virtual DbSet<Careerhistory> Careerhistories { get; set; }
        public virtual DbSet<CohortProcedureAssignment> CohortProcedureAssignments { get; set; }
        public virtual DbSet<Cohort> Cohorts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DataEntry> DataEntries { get; set; }
        public virtual DbSet<DataEntryDesign> DataEntryDesigns { get; set; }
        public virtual DbSet<DataEntryDetail> DataEntryDetails { get; set; }
        public virtual DbSet<DataEntryDetailValue> DataEntryDetailValues { get; set; }
        public virtual DbSet<DataEntryField> DataEntryFields { get; set; }
        public virtual DbSet<DataEntryOption> DataEntryOptions { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<MultiPARTProject> MultiPARTProjects { get; set; }
        public virtual DbSet<ProcedureDetailOptionField> ProcedureDetailOptionFields { get; set; }
        public virtual DbSet<ProcedureDetailOption> ProcedureDetailOptions { get; set; }
        public virtual DbSet<ProcedureDetail> ProcedureDetails { get; set; }
        public virtual DbSet<Procedure> Procedures { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<ResearchgroupCohortAssignment> ResearchgroupCohortAssignments { get; set; }
        public virtual DbSet<ResearchgroupInMultiPARTProject> ResearchgroupInMultiPARTProjects { get; set; }
        public virtual DbSet<Researchgroup> Researchgroups { get; set; }
        public virtual DbSet<SIUnit> SIUnits { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Strain> Strains { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UserDataentryAssignment> UserDataentryAssignments { get; set; }
        public virtual DbSet<UserInResearchgroup> UserInResearchgroups { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserProjectAssignment> UserProjectAssignments { get; set; }
    }
}
