//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiPARTProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MultiPARTProject()
        {
            this.AnimalHusbandries = new HashSet<AnimalHusbandry>();
            this.Cohorts = new HashSet<Cohort>();
            this.Procedures = new HashSet<Procedure>();
            this.ResearchgroupInMultiPARTProjects = new HashSet<ResearchgroupInMultiPARTProject>();
        }
    
        public int MultiPARTProjectID { get; set; }
        public string MultiPARTProjectName { get; set; }
        public string EthicalStatement { get; set; }
        public System.DateTime ProjectStartDate { get; set; }
        public System.DateTime ProjectCompletionDateExpected { get; set; }
        public Nullable<System.DateTime> ProjectComletionDate { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public System.DateTimeOffset LastUpdatedOn { get; set; }
        public int LastUpdatedBy { get; set; }
        public string Objectives { get; set; }
        public string Background { get; set; }
        public Nullable<int> LogoID { get; set; }
        public string AnalysisPlan { get; set; }
        public string Funding { get; set; }
        public bool Completed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalHusbandry> AnimalHusbandries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cohort> Cohorts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procedure> Procedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResearchgroupInMultiPARTProject> ResearchgroupInMultiPARTProjects { get; set; }
    }
}
