//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureDetailOptionField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcedureDetailOptionField()
        {
            this.ProcedureDetailOptions = new HashSet<ProcedureDetailOption>();
            this.ProcedureDetails = new HashSet<ProcedureDetail>();
        }
    
        public int ProcedureDetailOptionFieldID { get; set; }
        public Nullable<int> ProcedurePurposeOrTypeID { get; set; }
        public string ProcedureDetailOptionFieldName { get; set; }
        public int ProcedureDetailFieldTypeID { get; set; }
        public string Status { get; set; }
        public bool Multiple { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureDetailOption> ProcedureDetailOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureDetail> ProcedureDetails { get; set; }
    }
}
