//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.BehavioralScores = new HashSet<BehavioralScore>();
        }
    
        public int QuestionID { get; set; }
        public string SectionNumber { get; set; }
        public string Content { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> ChecklistID { get; set; }
        public string Status { get; set; }
        public int MaxScore { get; set; }
        public int MinScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehavioralScore> BehavioralScores { get; set; }
        public virtual ProcedureDetailOption ProcedureDetailOption { get; set; }
    }
}
