//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchgroupInMultiPARTProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResearchgroupInMultiPARTProject()
        {
            this.UserProjectAssignments = new HashSet<UserProjectAssignment>();
        }
    
        public int ResearchgroupInMultiPARTProjectID { get; set; }
        public int MultiPARTProjectMultiPARTProjectID { get; set; }
        public int ResearchgroupResearchgroupID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTimeOffset LastUpdatedOn { get; set; }
        public int ResearchgroupRoleinMultiPARTProjectID { get; set; }
    
        public virtual MultiPARTProject MultiPARTProject { get; set; }
        public virtual Researchgroup Researchgroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProjectAssignment> UserProjectAssignments { get; set; }
    }
}
