//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public string UnitSymbol { get; set; }
        public float ConversionFactor { get; set; }
        public int SIID { get; set; }
        public string Status { get; set; }
    
        public virtual SIUnit SIUnit { get; set; }
    }
}
