//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.Careerhistories = new HashSet<Careerhistory>();
            this.UserDataentryAssignments = new HashSet<UserDataentryAssignment>();
            this.UserInResearchgroups = new HashSet<UserInResearchgroup>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string ForeName { get; set; }
        public string SurName { get; set; }
        public string Email { get; set; }
        public string Details { get; set; }
        public string Status { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedOn { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Careerhistory> Careerhistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDataentryAssignment> UserDataentryAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInResearchgroup> UserInResearchgroups { get; set; }
    }
}
