//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPART
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProjectAssignment
    {
        public int UserProjectAssignmentID { get; set; }
        public int ResearchgroupInMultiPARTProjectResearchgroupInMultiPARTProjectID { get; set; }
        public int UserInResearchgroupUserInResearchgroupID { get; set; }
        public Nullable<int> UserRoleinProjectID { get; set; }
        public string Status { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTimeOffset LastUpdatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ResearchgroupInMultiPARTProject ResearchgroupInMultiPARTProject { get; set; }
        public virtual UserInResearchgroup UserInResearchgroup { get; set; }
    }
}
