// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class animaladministration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(animaladministration));
        
        string IMigrationMetadata.Id
        {
            get { return "201508041456143_animaladministration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
