// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class procedurepurposeOrtype1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(procedurepurposeOrtype1));
        
        string IMigrationMetadata.Id
        {
            get { return "201506051336210_procedurepurposeOrtype1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
