// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDataEntryIdforeignkeyproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDataEntryIdforeignkeyproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201506041508593_AddDataEntryId foreign key property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
