// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FieldNameChangesProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FieldNameChangesProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201507300935418_FieldNameChangesProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
