// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class speciesname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(speciesname));
        
        string IMigrationMetadata.Id
        {
            get { return "201506021119536_speciesname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
