// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ManuallyUpdatedDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManuallyUpdatedDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201506011328419_ManuallyUpdatedDatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
