// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class file : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(file));
        
        string IMigrationMetadata.Id
        {
            get { return "201506041745570_file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
