// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IngnorePendings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IngnorePendings));
        
        string IMigrationMetadata.Id
        {
            get { return "201507300934462_IngnorePendings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
