// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deleteadministrationmethodFromProcedure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteadministrationmethodFromProcedure));
        
        string IMigrationMetadata.Id
        {
            get { return "201506111535136_delete administrationmethodFromProcedure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
