// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class spelling : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(spelling));
        
        string IMigrationMetadata.Id
        {
            get { return "201506031841565_spelling"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
