// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class proceduredetailfieldtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(proceduredetailfieldtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201506021455052_proceduredetailfieldtype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
