// <auto-generated />
namespace MultiPART.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class administrationid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(administrationid));
        
        string IMigrationMetadata.Id
        {
            get { return "201508051436224_administrationid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
